[40기 - 전민식] Assignment 3: Express API - CRUD
wecode-bootcamp-korea/40-backend-westagram-2 pull request #11
Opened 2022-11-24 12:36 UTC by minsicko

## 수정 사항 간략한 한줄 요약
- 6가지 endpoints 작성
		 
## 수정 사항들 자세한 내용
- 게시글 등록
- 전체 게시글 조회
- 유저 게시글 조회
- 게시글 수정
- 게시글 삭제
- 좋아요 누르기

## 기타 질문 및 특이 사항
- 알아볼것:
- Promise 
- Middleware usage
- 구체적인 DQL Syntax (arrays, object)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
![db signup test](https://user-images.githubusercontent.com/111173900/203786082-60a7ce4e-f506-4ef8-9a28-b31869ca00a0.png)

2022-11-28 04:31 UTC, kyeongraekim requested changes

2022-11-28 04:31 UTC, kyeongraekim commented on minsik/app.js
> +//app.use(morgan('tiny'));
해당 내용 불필요한 주석처리가 보입니다. 수정해주세요!

2022-11-28 04:31 UTC, kyeongraekim commented on minsik/app.js
> +//const morgan = require("morgan");
해당 내용 불필요한 주석처리가 보입니다. 수정해주세요!

2022-11-28 04:31 UTC, kyeongraekim commented on minsik/app.js
> +const { DataSource, SimpleConsoleLogger } = require('typeorm');
- 현재 파일 상에서 사용하지 않는 모듈을 불러오는 행위는 지양해주세요. SimpleConsoleLogger의 용례가 불분명해보입니다!

2022-11-28 04:31 UTC, kyeongraekim commented on minsik/db/schema.sql
> +/*!40103 SET TIME_ZONE='+00:00' */;
불필요한 스키마 파일이 올라오지 않게 재수정해주세요!

2022-11-28 04:31 UTC, kyeongraekim commented on minsik/db/migrations/20221124075109_likes.sql
> +CREATE TABLE IF NOT EXISTS likes (
- 처음부터  likes 테이블을 만들고 데이터베이스를 설계하셔도 됩니다. 불필요한 if not 조건처리가 눈에 띄는데 해당 내용에 특별한 목적이 있으실까요?

2022-11-28 04:31 UTC, kyeongraekim commented on minsik/db/migrations/20221124075109_likes.sql
> +    FOREIGN KEY (likes_post) REFERENCES posts(id)
- 좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
- 하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
- 지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
- 이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-11-28 07:37 UTC, minsicko commented on minsik/db/migrations/20221124075109_likes.sql
> +CREATE TABLE IF NOT EXISTS likes (
dbmate migration이 정상적으로 처리가 안돼서 조건문을 사용해봤습니다. dbmate 처리됐고 조건문도 지웠습니다.

2022-11-29 06:14 UTC, kyeongraekim requested changes

2022-11-29 06:14 UTC, kyeongraekim commented on minsik/db/migrations/20221124075109_likes.sql
> +    FOREIGN KEY (likes_post) REFERENCES posts(id)
해당 부분은 아직 수정이 안되어있네요! [다음 링크](https://stackoverflow.com/questions/15800250/add-unique-constraint-to-combination-of-two-columns)를 보고 참고하여 수정해주세요!~

2022-11-29 07:35 UTC, minsicko commented
"[40기 - 전민식] Assignment 3: Express API - CRUD Completed Fix Requests" commit에 좋아요 기능에 대한 수정 했는데 확인 부탁드릴게요!

<img width="1055" alt="Screen Shot 2022-11-29 at 4 27 15 PM" src="https://user-images.githubusercontent.com/111173900/204465533-de18ba58-6feb-45a9-a2e3-cb02ea4e35c3.png">

2022-11-29 08:58 UTC, kyeongraekim approved these changes
LGTM~ 이제 레이어드 패턴을 적용하여 feature/layered-pattern 정도의 브랜치에 새롭게 리팩토링해주신 코드를 푸시해주세요!~

2022-11-29 08:58 UTC, merged