[40기 - 이정우] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/40-backend-westagram-2 pull request #2
Opened 2022-11-22 05:07 UTC by dozksms

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 생성

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 성공시 201  user_created!  반환
- 필수 데이터값이 없을시 400 반환
‎## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
<img width="861" alt="데이터 값 들어온것" src="https://user-images.githubusercontent.com/110329696/203226618-a1637abd-839f-4372-9f65-d62aff92d7cc.png">

2022-11-23 08:03 UTC, kyeongraekim requested changes

2022-11-23 08:03 UTC, kyeongraekim commented on leeJungWoo/app.js
> +const myDatasource = new DataSource({
- myDataSource 보다는 appDataSource , mysqlDataSource 혹은 간결하게 database로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

2022-11-23 08:03 UTC, kyeongraekim commented on leeJungWoo/db/migrations/20221122023354_create_users_table.sql
> +  `email` varchar(200) NOT NULL,
- email은 중복가입이 불가하게 보통 되어있습니다. 해당 내용에 고유값 설정(중복 입력제한)을 걸어주세요!

2022-11-23 08:03 UTC, kyeongraekim commented on leeJungWoo/db/migrations/20221122023417_create_likes_table.sql
> +
이곳도 한명의 유저가 특정 Post에 중복제한을 걸 수 없게 constraint 제한을 걸어주세요!~

2022-11-24 05:13 UTC, kyeongraekim submitted a review, later dismissed

2022-11-24 05:13 UTC, kyeongraekim commented on leeJungWoo/db/migrations/20221122023354_create_users_table.sql
> +  `email` varchar(200) NOT NULL,
- 해당 내용 수정이 아직 반영 전이네요!~

2022-11-24 05:13 UTC, kyeongraekim commented on leeJungWoo/db/migrations/20221122023417_create_likes_table.sql
> +
이곳에서 제가 의도한 코드의 생김새는 다음과 같습니다. 한번 아래의 내용이 어떤 의미를 지니고 있는지 곱씹어주시고 수정시 반영해주세요!
```javascript
ALTER TABLE likes ADD CONSTRAINT constraint_likes_unique UNIQUE (user_id, post_id);
```

2022-11-25 01:46 UTC, sangwoong03 requested changes

2022-11-25 01:46 UTC, sangwoong03 commented on leeJungWoo/db/migrations/20221123083825_users_table_update.sql
> +alter table users add unique index (email);
정우님! unique index 라는 속성을 지정한 이유가 있을까요??

2022-11-25 04:15 UTC, dozksms commented on leeJungWoo/db/migrations/20221123083825_users_table_update.sql
> +alter table users add unique index (email);
앞선 피드백에서 email 중복가입 안되게끔 table을 수정하는게 좋겠다고 피드백 주셔서 email column에 unique값 추가했습니다!

2022-11-25 08:15 UTC, sangwoong03 requested changes

2022-11-25 08:15 UTC, sangwoong03 commented on leeJungWoo/app.js
> +const mysqlDatasource = new DataSource({
```suggestion
const appDatasource = new DataSource({
```

데이터베이스 클라이언트에 대한 정보도 노출하기 않기 위해 환경변수 파일에서 데이터베이스의 타입도 관리하고 있습니다.

`mysqlDatasource`라는 변수명 보다는 다른 변수명을 사용해주세요!

2022-11-25 08:16 UTC, sangwoong03 approved these changes
LGTM 👍

2022-11-25 08:17 UTC, merged