[40기 - 전민식] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/40-backend-westagram-2 pull request #5
Opened 2022-11-23 12:28 UTC by minsicko

## 수정 사항 간략한 한줄 요약
- User 회원가입 엔드포인트 추가
		 
## 수정 사항들 자세한 내용
- 클라이언트와 통신 성공 (httpie)
- POST 메소드를 사용해서 유저의 정보를 백엔드 서버에 전달
- 201 http 상태코드 반환
- http response로 반환하는 JSON 데이터 확인
- db에 저장확인 (스크린샷 첨부)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

![db signup endpoint test](https://user-images.githubusercontent.com/111173900/203546816-f9b001b5-af00-4285-9623-164a7c8908c2.png)

2022-11-24 05:08 UTC, kyeongraekim requested changes

2022-11-24 05:08 UTC, kyeongraekim commented on minsik/db/schema.sql
> +  `version` varchar(255) COLLATE latin1_bin NOT NULL,
-  로컬환경에서 개인의 시점에 맞는 schema 파일이 완성됨으로, schema 파일은 .gitignore 파일에 추가해서 깃헙에서는 공유 안되게 수정해주세요!

2022-11-24 05:08 UTC, kyeongraekim submitted a review, later dismissed

2022-11-24 05:08 UTC, kyeongraekim commented on minsik/db/migrations/20221123070801_users.sql
> +    email VARCHAR(200) NOT NULL,
- 이메일의 중복 기입이 되지 않게 unique 설정을 걸어주세요!

2022-11-25 01:57 UTC, sangwoong03 requested changes

2022-11-25 01:57 UTC, sangwoong03 commented on minsik/db/migrations/20221123070801_users.sql
> +    UNIQUE (email)
```suggestion
    ATLER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);
```

위의 코드와 같이 제약 조건을 지정해 줄 수도 있을 것 같습니다!

2022-11-25 01:57 UTC, sangwoong03 commented on minsik/db/schema.sql
> +  `version` varchar(255) COLLATE latin1_bin NOT NULL,
해당 부분은 수정이 아직 안되어 있네요! 반영부탁드립니다~!

2022-11-25 04:24 UTC, minsicko commented
[Express API - 유저 회원가입 하기 수정 2] - 캐시 삭제 하고 푸시 했습니다

2022-11-25 08:26 UTC, sangwoong03 requested changes

2022-11-25 08:26 UTC, sangwoong03 commented on minsik/db/migrations/20221125035213_alterUsersTable.sql
> +    ADD CONSTRAINT email UNIQUE (email);
- 해당 컬럼에 Unique Constraint가 필요한 경우
    - 해당 컬럼은 중복되면 안되는 데이터를 저장하는 컬럼입니다. 따라서 unique contraint를 추가해주셔야 합니다.
    - `CASE` 이미 unique 제약 조건을 작성하였으나, CONSTRAINT 키워드를 활용하지 않은 경우
        - 제약에는 이름을 붙일 수 있습니다. 제약에 이름을 붙이면 나중에 관리하기 쉬워지므로 가능한 한 이름을 붙이도록 해주세요! 제약 이름은 CONSTRAINT 키워드를 이용해서 다음과 같이 지정합니다.
        
        ```sql
        CONSTRAINT users_email_ukey UNIQUE (email)
        
        # ex 외래키 ) CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
        
        # description) CONSTRAINT 테이블명_컬럼명_키타입 [제약조건] (컬럼명) 
        ```

민식님 해당 부분 참고하셔서 제약 조건의 이름을 관리하기 용이한 이름으로 변경해보면 좋을 것 같네요~!

2022-11-25 09:04 UTC, sangwoong03 approved these changes
LGTM 👍

2022-11-25 09:04 UTC, merged