Feature/hwang jeong soo sign up
wecode-bootcamp-korea/40-backend-westagram-2 pull request #8
Opened 2022-11-24 09:30 UTC by JeongSooHHH

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 회원가입 입니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 유저 회원가입 내용

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [X ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-25 02:22 UTC, sangwoong03 requested changes

2022-11-25 02:22 UTC, sangwoong03 commented on hwangJeongSoo/db/schema.sql
> +
schema.sql은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 .gitignore에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

2022-11-25 02:22 UTC, sangwoong03 commented on hwangJeongSoo/app.js
> +);
```suggestion
await myDataSource.query(
    `INSERT INTO users(
        name,
        email,
        profile_image,
        password
    ) VALUES (?, ?, ?, ?, ?);
    `,
    [ name, email, profile_image, password ]
); 
```
데이터베이스 users 테이블 스키마를 보면 id 컬럼은 `auto_increment` 속성이 지정되어 있네요!

데이터가 생성될 때마다 해당 데이터에 맞는 id 값이 자동으로 생성되기 때문에 직접 값을 넣어주지 않아도 됩니다!

2022-11-25 02:22 UTC, sangwoong03 commented on hwangJeongSoo/db/migrations/20221124072109_create_users_table.sql
> +        email VARCHAR(200) NOT NULL,
보통 email을 중복 가입이 불가능하게 설정되어 있을 것입니다.

email 컬럼에 unique 속성을 추가해주세요!

2022-11-25 02:22 UTC, sangwoong03 commented on hwangJeongSoo/db/migrations/20221124072120_create_likes_table.sql
> +        user_id INT NOT NULL,
유저가 특정 게시물에 좋아요를 두번 누르면 좋아요는 취소가 됩니다.

즉 user_id 값이 중복으로 들어올 수 없다는 것을 의미합니다.

해당 user_id 컬럼에 unique 속성을 추가해주세요!

2022-11-25 02:22 UTC, sangwoong03 commented on hwangJeongSoo/package.json
> +  }
```suggestion
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "mysql": "^2.18.1",
    "typeorm": "^0.3.10"
  },
  devDependencies: {
     "nodemon": "^2.0.20",
     "morgan": "^1.10.0"
  }
```

- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.
- mysql & mysql2 드라이버 패키지는 서로 동일한 기능을 하는 패키지 입니다. 따라서 둘 중 하나를 선택하여 설치를 진행해주세요.

2022-11-25 02:23 UTC, sangwoong03 commented on hwangJeongSoo/app.js
> +const myDataSource = new DataSource({
myDataSource 보다는 appDataSource , mysqlDataSource 혹은 간결하게 database로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

2022-11-25 08:33 UTC, sangwoong03 requested changes

2022-11-25 08:33 UTC, sangwoong03 commented on hwangJeongSoo/.gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/linux,macos,webstorm,node,visualstudiocode,windows,dotenv
```suggestion
# End of https://www.toptal.com/developers/gitignore/api/linux,macos,webstorm,node,visualstudiocode,windows,dotenv

db/schema.sql
```

db/schema.sql 파일이 github에 공유되는 것을 방지하기 위해 `.gitignore`에 db/schema.sql을 추가해주세요!

2022-11-25 08:33 UTC, sangwoong03 commented on hwangJeongSoo/app.js
> +//8. 좋아요 누르기 api
회원가입과 관련된 PR에는 하나의 기능만 올라올 수 있도록 연습해주세요!

해당 코드는 3번째 PR에서 올릴 수 있도록 수정 부탁드립니다~!

2022-11-25 08:33 UTC, sangwoong03 commented on hwangJeongSoo/app.js
> +    })
코드의 가독성을 높이는 방법에는 여러가지가 있습니다.

그 중에서 들여쓰기 (indentation)는 해당 코드가 어떤 함수에 포함되는지 확인할 수 있을 것입니다.

마이너한 부분이지만 가독성이 좋은 코드로 수정해주세요~!
```suggestion
//2. signup
app.post("/signup", async(req, res, next)=>{
    const { name, email, profile_image, password } = req.body

    await myDataSource.query(
        `INSERT INTO users(
            name,
            email,
            profile_image,
            password
        ) VALUES (?, ?, ?, ?);
        `,
        [ name, email, profile_image, password ]
    ); 
     res.status(201).json({ message : "successfully created"});
})
```

2022-11-25 08:33 UTC, sangwoong03 commented on hwangJeongSoo/db/migrations/20221124072109_create_users_table.sql
> +        UNIQUE (email)
```suggestion
        CONSTRAINT users_email_ukey UNIQUE (email)
```

- `CASE` 이미 unique 제약 조건을 작성하였으나, CONSTRAINT 키워드를 활용하지 않은 경우
    - 제약에는 이름을 붙일 수 있습니다. 제약에 이름을 붙이면 나중에 관리하기 쉬워지므로 가능한 한 이름을 붙이도록 해주세요! 제약 이름은 CONSTRAINT 키워드를 이용해서 다음과 같이 지정합니다.
    
    ```sql
    CONSTRAINT users_email_ukey UNIQUE (email)
    
    # ex 외래키 ) CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
    
    # description) CONSTRAINT 테이블명_컬럼명_키타입 [제약조건] (컬럼명) 
    ```

2022-11-25 08:33 UTC, sangwoong03 commented on hwangJeongSoo/db/migrations/20221124072120_create_likes_table.sql
> +        UNIQUE (user_id)
해당 부분도 위의 리뷰를 참고하여 수정해주세요~!

2022-11-28 03:33 UTC, kyeongraekim commented
package.json 패키지 관리가 잘못 되어서 컨플릭트가 난것 같습니다!~

2022-11-28 03:53 UTC, JeongSooHHH commented on hwangJeongSoo/db/schema.sql
> +
.

2022-11-28 03:54 UTC, JeongSooHHH commented on hwangJeongSoo/app.js
> +);
.

2022-11-28 03:55 UTC, JeongSooHHH commented on hwangJeongSoo/db/migrations/20221124072109_create_users_table.sql
> +        email VARCHAR(200) NOT NULL,
.

2022-11-28 03:56 UTC, JeongSooHHH commented on hwangJeongSoo/package.json
> +  }
.

2022-11-28 05:18 UTC, JeongSooHHH commented
package.json 내에 mysql, mysql2 같은 기능 중복사용으로 인하여 comflict 발생하여 mysql2 제거하였습니다.

2022-11-29 06:13 UTC, kyeongraekim approved these changes
다음 과제 진행을 위해 선 머지 해드리겠습니다. 다음 푸시 때는 꼭 schema.sql파일을 깃헙상에서 공유되지 않게 수정해서 올려주세요!

2022-11-29 06:13 UTC, merged